# Generated by Django 3.1.2 on 2024-06-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240617_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolusuario',
            options={'permissions': (('cliente_permiso', 'Permiso para Cliente'), ('encargado_taller_permiso', 'Permiso para Encargado de Taller'), ('administrador_permiso', 'Permiso para Administrador'))},
        ),
    ]
