# Generated by Django 5.0.6 on 2024-07-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuariocustom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='respuestaTicket',
            field=models.TextField(blank=True, null=True),
        ),
    ]
